### ISSUE TITLE
PHP Fatal error when deactivating/reactivating plugin

### ISSUE THREAD

**Issue by laerm** [cccraig/MugShot#47]
When reactivating the disabled plugin, I get the following error:

```bash
[Sat Feb 04 18:04:58.836146 2023] [proxy_fcgi:error] [pid 737805] [client 178.39.186.97:57306] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate entry 'MugShot' for key 'piwigo_config.PRIMARY' in /home/redacted/public_html/include/dblayer/functions_mysqli.inc.php:132\nStack trace:\n#0 /home/redacted/public_html/include/dblayer/functions_mysqli.inc.php(132): mysqli->query()\n#1 /home/redacted/public_html/plugins/MugShot/include/helpers.php(84): pwg_query()\n#2 /home/redacted/public_html/plugins/MugShot/maintain.inc.php(40): create_facetag_table()\n#3 /home/redacted/public_html/plugins/MugShot/maintain.inc.php(65): MugShot_maintain->install()\n#4 /home/redacted/public_html/admin/include/plugins.class.php(195): MugShot_maintain->activate()\n#5 /home/redacted/public_html/include/ws_functions/pwg.extensions.php(71): plugins->perform_action()\n#6 /home/redacted/public_html/include/ws_core.inc.php(600): ws_plugins_performAction()\n#7 /home/redacted/public_html/include/ws_protocols/rest_handler.php(41): PwgServer->invoke()\n#8 /home/redacted/public_html/inc...', referer: https://www.redacted.com/admin.php?page=plugins&tab=installed
```
I need to then remove the MugShot entry from the DB in order to reactivated the plugin. Piwigo 13.5.0, PHP 8.2.2.

Thanks for a great plugin!

**Comment by laerm** [comment]
Changing helpers.php file, line 84

from

`$configQuery = 'INSERT INTO ' . CONFIG_TABLE . ' (param,value,comment) VALUES ("MugShot","","MugShot configuration values");';`

to 

`$configQuery = 'INSERT IGNORE INTO ' . CONFIG_TABLE . ' (param,value,comment) VALUES ("MugShot","","MugShot configuration values");';`

Fixes the issue

**Comment by laerm** [comment]
Hmm, seems it's currently "REPLACE INTO" in the current codebase. Not sure Why my file hadn't updated... Closing as it's fixed.
